### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by 13098873679** [hit-moodle/moodle-local_onlinejudge#89]
你好，我按照你的方法安装好插件之后在“添加一个活动”里没有找到“在线测评”，请问是怎么回事，您知道不？

**Comment by LIU3379** [comment]
在作业-反馈类型中，和以前的不太一样，您的插件安装好了吗，我遇到个问题，评测状态一直是[[status-1]]，您遇到过

**Comment by andrewnaguib** [comment]
Does the problem persists?

**Comment by caicaixiaoya** [comment]
想问一下，我把压缩包直接放在Moodle里的插件管理里面直接进行安装，但是反馈里面没有在线评测是哪里出错了吗

**Comment by ndrwnaguib** [comment]
I am sorry @caicaixiaoya, I do not speak Chinese. Could you please restate your comment in English?

**Comment by caicaixiaoya** [comment]
> 对不起@caicaixiaoya， 我不说中文。您能用英语重述一下您的评论吗？

fatal: Remote branch OJ_VERSION not found in upstream origin    
What does this problem mean? How to solve it

**Comment by ndrwnaguib** [comment]
`OJ_VERSION` is a placeholder for an actual branch name. For example, try instead `OJ_40_STABLE`. On Sep 1, 2023, at 22:55, caicaixiaoya ***@***.***> wrote:﻿

***@***.***， 我不说中文。您能用英语重述一下您的评论吗？

fatal: Remote branch OJ_VERSION not found in upstream origin
What does this problem mean? How to solve it

**Comment by caicaixiaoya** [comment]
> 

Is there any connection between this branch and the Moodle system version?
 My Moodle system is version 3.9

**Comment by ndrwnaguib** [comment]
There is no connection between the branch names yet. `OJ_40_STABLE` should work fine on Moodle 3.7-4.2. On Sep 1, 2023, at 23:07, caicaixiaoya ***@***.***> wrote:﻿


Is there any connection between this branch and the Moodle system version?
My Moodle system is version 3.9

**Comment by caicaixiaoya** [comment]
> There is no connection between the branch names yet. `OJ_40_STABLE` should work fine on Moodle 3.7-4.2. On Sep 1, 2023, at 23:07, caicaixiaoya ***@***.***> wrote:﻿ Is there any connection between this branch and the Moodle system version? My Moodle system is version 3.9 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
"If you would like to use sandbox judge engine"
I wonder if I can skip this

**Comment by ndrwnaguib** [comment]
You can. Do you have valid access credentials to Sphere Engine?

**Comment by caicaixiaoya** [comment]
> 你可以。您是否拥有 Sphere Engine 的有效访问凭据？

I don't know what that credential is, so maybe it's not

**Comment by caicaixiaoya** [comment]
"In command prompt, write php.exe MOODLE_PATH\local\onlinejudge\cli\judged.php -v, to launch the [Judge Daemon](https://github.com/hit-moodle/moodle-local_onlinejudge#judge-daemon)."
In this step I encountered such a mistake
"Fatal error: During inheritance of IteratorAggregate: Uncaught ArgumentCountError: Too few arguments to function default_error_handler(), 4 passed in D:\Moodle3.9\server\moodle\lib\navigationlib.php on line 897 and exactly 5 expected in D:\Moodle3.9\server\moodle\lib\setuplib.php:425"
How to solve it?

**Comment by caicaixiaoya** [comment]
I have solved all the problems, but in the plugin management, this online evaluation of the job/feedback plugin is disabled, how to solve this problem
